/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFramse.java to edit this template
 */
package ucr.ac.cr.proyecto2.view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import ucr.ac.cr.proyecto2.controller.ControllerLogin;


/**
 *
 * @author User
 */
public class GUIAdminUser extends javax.swing.JFrame {

     TableRowSorter<TableModel> sorter;
    /**
     * Creates new form GUIReport
     */
    public GUIAdminUser() {
        initComponents();
        TextPrompt placeHolderUser = new TextPrompt("Insert an username", txtFilterUsers);
    }
    
    public int getSelectRow(){
        return tblRegisteredUsers.getSelectedRow();
    }//fin del metodo
    
    public void listenButtons(ActionListener controller){
        this.btModify.addActionListener(controller);
      
    }
    
    public void listenMouse(MouseListener controller){
        this.tblRegisteredUsers.addMouseListener(controller);
    }
    
    public String getSearch(){// EJRM
        return this.txtFilterUsers.getText();
    }
    
    public void setCode(String code){// EJRM
        this.txtFilterUsers.setText(code);
    }
    
    public void setDataTable(String[][] data, String[] title)
    {
       DefaultTableModel model = new DefaultTableModel(data, title);
       this.tblRegisteredUsers.setModel(model);
       this.tblRegisteredUsers.setAutoCreateRowSorter(true);
       this.sorter = new TableRowSorter<>(model);
       this.tblRegisteredUsers.setRowSorter(sorter);
       this.jScrollPane2.setViewportView(this.tblRegisteredUsers);
    }
    
    public String[] getDataRow(){
        
       String[] data = new String[this.tblRegisteredUsers.getColumnCount()];
       int selectedRow = this.tblRegisteredUsers.getSelectedRow();
       
        for (int i = 0; i < data.length; i++) 
        {
            data[i] = this.tblRegisteredUsers.getValueAt(selectedRow, i).toString();
        }
        return data;
    }
    
   
    

    public static void getMessage(String msg){
        JOptionPane.showMessageDialog(null, msg);
    }
    
    public void unSelectRow(){
        tblRegisteredUsers.clearSelection();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtFilterUsers = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btModify = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegisteredUsers = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btClose = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User settings");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFilterUsers.setForeground(new java.awt.Color(51, 51, 51));
        txtFilterUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterUsersActionPerformed(evt);
            }
        });
        txtFilterUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterUsersKeyReleased(evt);
            }
        });
        jPanel2.add(txtFilterUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 81, 241, -1));

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Search:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 61, 27));

        jButton2.setBackground(new java.awt.Color(153, 255, 204));
        jButton2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 30, 30));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Users settings");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Registered users");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        btModify.setBackground(new java.awt.Color(153, 255, 204));
        btModify.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btModify.setForeground(new java.awt.Color(51, 51, 51));
        btModify.setText("Modify");
        btModify.setActionCommand("Modify");
        btModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifyActionPerformed(evt);
            }
        });
        jPanel2.add(btModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 90, 30));

        tblRegisteredUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegisteredUsers.setToolTipText("");
        tblRegisteredUsers.setAutoscrolls(false);
        tblRegisteredUsers.setSelectionBackground(new java.awt.Color(153, 255, 204));
        jScrollPane2.setViewportView(tblRegisteredUsers);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 150, 516, 180));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 530, 200));

        btClose.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        btClose.setForeground(new java.awt.Color(0, 102, 102));
        btClose.setText("Close");
        jPanel2.add(btClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 580, 405));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        ControllerLogin login = new ControllerLogin();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtFilterUsersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterUsersKeyReleased
        this.sorter.setRowFilter(RowFilter.regexFilter("(?i)"+this.txtFilterUsers.getText(), 0));
    }//GEN-LAST:event_txtFilterUsersKeyReleased

    private void txtFilterUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterUsersActionPerformed

    private void btModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btModifyActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btClose;
    private javax.swing.JButton btModify;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRegisteredUsers;
    private javax.swing.JTextField txtFilterUsers;
    // End of variables declaration//GEN-END:variables
}
