/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.proyecto2.view;

import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import ucr.ac.cr.proyecto2.controller.ControllerAdminUser;
import ucr.ac.cr.proyecto2.controller.ControllerNewAccount;
import ucr.ac.cr.proyecto2.controller.TbUsuariosJpaController;
import ucr.ac.cr.proyecto2.model.TbUsuarios;

/**
 *
 * @author User
 */
public class GUIModifyAccount extends javax.swing.JFrame {

    /**
     * Creates new form GUINewAccount
     */
    public GUIModifyAccount() {
        initComponents();
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(rbtnAdmin);
        buttonGroup.add(rbtnUser);
        buttonGroup.add(rbtnAdminWeb);
        this.rbtnUser.setSelected(true);
        TextPrompt placeHolderUsername = new TextPrompt("Username", txtUsernameNA);
        TextPrompt placeHolderPassword = new TextPrompt("Password", txtPasswordNA);
        TextPrompt placeHolderName = new TextPrompt("Name", txtNameNA);
       
    }
    
    public void setData(TbUsuarios usuario){
        txtUsernameNA.setText(usuario.getUsername());
        txtPasswordNA.setText(usuario.getPassword());
        txtNameNA.setText(usuario.getName());
        if(usuario.getProfile().equals("AdminJava")){
            this.rbtnAdmin.setSelected(true);
        } else if(usuario.getProfile().equals("User")){
            this.rbtnUser.setSelected(true);
        } else {
            this.rbtnAdminWeb.setSelected(true);
        }
    }
    
   
    
    public void listen(ActionListener controller)
    {
        this.btDelete.addActionListener(controller);
        this.btSearch.addActionListener(controller);
        this.btModify.addActionListener(controller);
        this.btAdd.addActionListener(controller);
        
        
    }
     
    
    public boolean getSelectrbUser(){
        return this.rbtnUser.isSelected();
    }
     
    public boolean getSelectrbAdmin(){
        return this.rbtnAdmin.isSelected();
    }
    public boolean getSelectrbAdminWeb(){
        return this.rbtnAdminWeb.isSelected();
    }
    
     
    public String getRbUser(){
      return this.rbtnUser.toString();
    }
     
    public String getRbAdmin(){
       return this.rbtnAdmin.toString();
    }
     
 
    public boolean txtIsEmptyUser(){
        if(this.txtPasswordNA.getText().isBlank() || this.txtUsernameNA.getText().isBlank()){
            return true;
        }
        return false;
    }
    
    public void setUsuario(String usuario){
        TbUsuariosJpaController jpaUsuarios = new TbUsuariosJpaController();
        
                if (jpaUsuarios.search(usuario) != null) {
                    this.setData(jpaUsuarios.search(usuario));
                } else {
                    this.getMessage("No se encontro ningun usuario con el userName");
                }

           
    }
    
 

    public void getMessage(String message){
        JOptionPane.showMessageDialog(null,message);
    }
    
    public String getTxtUsername(){
        return this.txtUsernameNA.getText();
    }
    public String getTxtName(){
        return this.txtNameNA.getText();
    }
    
    public String getTxtPassword(){
        return this.txtPasswordNA.getText();
    }
    
   
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsernameNA = new javax.swing.JTextField();
        txtPasswordNA = new javax.swing.JTextField();
        txtNameNA = new javax.swing.JTextField();
        btDelete = new javax.swing.JButton();
        btSearch = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        btModify = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        rbtnAdmin = new javax.swing.JRadioButton();
        rbtnAdminWeb = new javax.swing.JRadioButton();
        rbtnUser = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create a new account");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        jLabel1.setText(" Account type");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 100, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        txtUsernameNA.setBackground(new java.awt.Color(51, 51, 51));
        txtUsernameNA.setForeground(new java.awt.Color(204, 204, 204));
        txtUsernameNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameNAActionPerformed(evt);
            }
        });
        jPanel4.add(txtUsernameNA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 160, 20));

        txtPasswordNA.setBackground(new java.awt.Color(51, 51, 51));
        txtPasswordNA.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.add(txtPasswordNA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 160, -1));

        txtNameNA.setBackground(new java.awt.Color(51, 51, 51));
        txtNameNA.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.add(txtNameNA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 160, -1));

        btDelete.setBackground(new java.awt.Color(204, 204, 204));
        btDelete.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btDelete.setForeground(new java.awt.Color(51, 51, 51));
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 90, -1));

        btSearch.setBackground(new java.awt.Color(204, 204, 204));
        btSearch.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btSearch.setForeground(new java.awt.Color(51, 51, 51));
        btSearch.setText("Search");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        jPanel4.add(btSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, -1));

        btClose.setBackground(new java.awt.Color(204, 204, 204));
        btClose.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btClose.setForeground(new java.awt.Color(51, 51, 51));
        btClose.setText("Close");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });
        jPanel4.add(btClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 80, -1));

        btModify.setBackground(new java.awt.Color(204, 204, 204));
        btModify.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btModify.setForeground(new java.awt.Color(51, 51, 51));
        btModify.setText("Modify");
        btModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifyActionPerformed(evt);
            }
        });
        jPanel4.add(btModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, -1));

        btAdd.setBackground(new java.awt.Color(204, 204, 204));
        btAdd.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        btAdd.setForeground(new java.awt.Color(51, 51, 51));
        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        jPanel4.add(btAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, -1));

        rbtnAdmin.setBackground(new java.awt.Color(255, 255, 255));
        rbtnAdmin.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        rbtnAdmin.setText("Admin Java");
        jPanel4.add(rbtnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        rbtnAdminWeb.setBackground(new java.awt.Color(255, 255, 255));
        rbtnAdminWeb.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        rbtnAdminWeb.setText("Admin Web");
        jPanel4.add(rbtnAdminWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        rbtnUser.setBackground(new java.awt.Color(255, 255, 255));
        rbtnUser.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        rbtnUser.setText("User");
        jPanel4.add(rbtnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 290, 330));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        this.dispose();
        ControllerAdminUser adminUser= new ControllerAdminUser();
    }//GEN-LAST:event_btCloseActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSearchActionPerformed

    private void btModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btModifyActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddActionPerformed

    private void txtUsernameNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameNAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameNAActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClose;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btModify;
    private javax.swing.JButton btSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rbtnAdmin;
    private javax.swing.JRadioButton rbtnAdminWeb;
    private javax.swing.JRadioButton rbtnUser;
    private javax.swing.JTextField txtNameNA;
    private javax.swing.JTextField txtPasswordNA;
    private javax.swing.JTextField txtUsernameNA;
    // End of variables declaration//GEN-END:variables
}
